<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registro</title>
</head>
<body>

    <h1>Registrarse</h1>

   <!-- ?=Utils::mostrarError('register')?-->

    <form action="index.php?c=Usuario&&a=save" method="POST">
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" required>

        <label for="apellidos">Apellidos</label>
        <input type="text" name="apellidos" required>

        <label for="email">Email</label>
        <input type="email" name="email" required>

        <label for="password">Contraseña</label>
        <input type="password" name="password" required>

        <input type="submit" name="submit" value="Registrarse">
    </form>

    <?php
         echo "<br> &nbsp; <a href='index.php'>Inicio</a>";

   ?>


</body>
</html>

