<h1>NUEVA NOTA</h1>

<!-- ?=Utils::mostrarError('register')?-->

 <form action="index.php?c=Notas&&a=crearNota" method="POST">
     <label for="titulo">Titulo</label>
     <input type="text" name="titulo" >

     <label for="descripcion">Descripcion</label>
     <input type="text" name="descripcion" >

     <label for="usuario_id">Usuario Id</label>
     <input type="text" name="usuario_id" >

     <input type="submit" name="submit" value="Nueva Nota">
 </form>

 <?php
   echo "<br> &nbsp; <a href='index.php'>Inicio</a>";

   ?>

